apiVersion: v2
name: ndb-operator
version: 0.1.0
kubeVersion: ">= 1.19.0"
description: A Helm chart for deploying the Oracle MySQL NDB Cluster Operator
appVersion: "0.1.0"
keywords:
  - NDB Operator
  - MySQL Cluster
  - NDB
  - Ndbcluster
maintainers:
  - name: Lakshmi Narayanan Sreethar
    email: lakshmi.narayanan.sreethar@oracle.com
