apiVersion: v2
name: ndb-operator
version: 1.0.11
kubeVersion: ">= 1.23.0-0"
description: A Helm chart for deploying the Oracle MySQL NDB Cluster Operator
appVersion: "8.0.42-1.0.11"
keywords:
  - NDB Operator
  - MySQL Cluster
  - NDB
  - Ndbcluster
home: https://github.com/mysql/mysql-ndb-operator
maintainers:
  - name: Paulo Silva
    email: paulo.p.silva@oracle.com
annotations:
  artifacthub.io/images: |
    - name: ndb-operator
      image: container-registry.oracle.com/mysql/community-ndb-operator:8.0.42-1.0.11
  artifacthub.io/crds: |
    - kind: NdbCluster
      version: v1
      name: ndbcluster.mysql.oracle.com
      displayName: MySQL NDB Cluster
      description: MySQL NDB Cluster configuration
  artifacthub.io/crdsExamples: |
    - apiVersion: mysql.oracle.com/v1
      kind: NdbCluster
      metadata:
        name: my-ndb
      spec:
        nodeCount: 2
        redundancyLevel: 2
        mysqlNode:
          nodeCount: 2
  artifacthub.io/license: UPL-1.0
  artifacthub.io/operator: "true"
  artifacthub.io/operatorCapabilities: Seamless Upgrades
