# Yaml file with default values for the NDB Operator templates

# default image, pull secret and pull policy
image: container-registry.oracle.com/mysql/community-ndb-operator:8.0.35-1.0.4
imagePullPolicy: IfNotPresent
imagePullSecretName:

# The operator is by default cluster-scoped.
# If this value is set to false, the operator will be namespace-scoped and
# will be watching for NdbCluster resource changes only in the namespace
# it is released into (controlled by helm's --namespace option).
clusterScoped: true
